/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chonk70703(props) {
  const { nodes, materials } = useGLTF('/70703.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
          position={[-3, -8, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
          position={[-2, -8, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
          position={[2, -8, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_3.geometry}
          material={nodes.mesh_3.material}
          position={[3, -8, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_4.geometry}
          material={nodes.mesh_4.material}
          position={[-3, -8, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_5.geometry}
          material={nodes.mesh_5.material}
          position={[-2, -8, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_6.geometry}
          material={nodes.mesh_6.material}
          position={[2, -8, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_7.geometry}
          material={nodes.mesh_7.material}
          position={[3, -8, 0]}
        />
      </group>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_8.geometry}
          material={nodes.mesh_8.material}
          position={[-2, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_9.geometry}
          material={nodes.mesh_9.material}
          position={[2, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_10.geometry}
          material={nodes.mesh_10.material}
          position={[-2, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_11.geometry}
          material={nodes.mesh_11.material}
          position={[2, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_12.geometry}
          material={nodes.mesh_12.material}
          position={[-2, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_13.geometry}
          material={nodes.mesh_13.material}
          position={[2, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_14.geometry}
          material={nodes.mesh_14.material}
          position={[-2, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_15.geometry}
          material={nodes.mesh_15.material}
          position={[2, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_16.geometry}
          material={nodes.mesh_16.material}
          position={[-3, -6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_17.geometry}
          material={nodes.mesh_17.material}
          position={[-2, -6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_18.geometry}
          material={nodes.mesh_18.material}
          position={[-1, -6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_19.geometry}
          material={nodes.mesh_19.material}
          position={[0, -6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_20.geometry}
          material={nodes.mesh_20.material}
          position={[1, -6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_21.geometry}
          material={nodes.mesh_21.material}
          position={[2, -6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_22.geometry}
          material={nodes.mesh_22.material}
          position={[3, -6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_23.geometry}
          material={nodes.mesh_23.material}
          position={[-3, -7, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_24.geometry}
          material={nodes.mesh_24.material}
          position={[-2, -7, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_25.geometry}
          material={nodes.mesh_25.material}
          position={[-1, -7, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_26.geometry}
          material={nodes.mesh_26.material}
          position={[1, -7, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_27.geometry}
          material={nodes.mesh_27.material}
          position={[2, -7, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_28.geometry}
          material={nodes.mesh_28.material}
          position={[3, -7, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_29.geometry}
          material={nodes.mesh_29.material}
          position={[-3, -6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_30.geometry}
          material={nodes.mesh_30.material}
          position={[-2, -6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_31.geometry}
          material={nodes.mesh_31.material}
          position={[-1, -6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_32.geometry}
          material={nodes.mesh_32.material}
          position={[0, -6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_33.geometry}
          material={nodes.mesh_33.material}
          position={[1, -6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_34.geometry}
          material={nodes.mesh_34.material}
          position={[2, -6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_35.geometry}
          material={nodes.mesh_35.material}
          position={[3, -6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_36.geometry}
          material={nodes.mesh_36.material}
          position={[2, -5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_37.geometry}
          material={nodes.mesh_37.material}
          position={[2, -4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_38.geometry}
          material={nodes.mesh_38.material}
          position={[2, -3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_39.geometry}
          material={nodes.mesh_39.material}
          position={[2, -2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_40.geometry}
          material={nodes.mesh_40.material}
          position={[-2, -2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_41.geometry}
          material={nodes.mesh_41.material}
          position={[-2, -3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_42.geometry}
          material={nodes.mesh_42.material}
          position={[-2, -4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_43.geometry}
          material={nodes.mesh_43.material}
          position={[-2, -5, -1]}
        />
      </group>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_44.geometry}
          material={nodes.mesh_44.material}
          position={[-3, -1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_45.geometry}
          material={nodes.mesh_45.material}
          position={[-2, -1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_46.geometry}
          material={nodes.mesh_46.material}
          position={[-1, -1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_47.geometry}
          material={nodes.mesh_47.material}
          position={[0, -1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_48.geometry}
          material={nodes.mesh_48.material}
          position={[1, -1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_49.geometry}
          material={nodes.mesh_49.material}
          position={[2, -1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_50.geometry}
          material={nodes.mesh_50.material}
          position={[3, -1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_51.geometry}
          material={nodes.mesh_51.material}
          position={[-4, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_52.geometry}
          material={nodes.mesh_52.material}
          position={[-3, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_53.geometry}
          material={nodes.mesh_53.material}
          position={[-1, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_54.geometry}
          material={nodes.mesh_54.material}
          position={[0, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_55.geometry}
          material={nodes.mesh_55.material}
          position={[1, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_56.geometry}
          material={nodes.mesh_56.material}
          position={[3, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_57.geometry}
          material={nodes.mesh_57.material}
          position={[4, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_58.geometry}
          material={nodes.mesh_58.material}
          position={[-5, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_59.geometry}
          material={nodes.mesh_59.material}
          position={[-4, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_60.geometry}
          material={nodes.mesh_60.material}
          position={[-3, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_61.geometry}
          material={nodes.mesh_61.material}
          position={[-1, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_62.geometry}
          material={nodes.mesh_62.material}
          position={[0, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_63.geometry}
          material={nodes.mesh_63.material}
          position={[1, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_64.geometry}
          material={nodes.mesh_64.material}
          position={[3, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_65.geometry}
          material={nodes.mesh_65.material}
          position={[4, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_66.geometry}
          material={nodes.mesh_66.material}
          position={[5, -3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_67.geometry}
          material={nodes.mesh_67.material}
          position={[-5, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_68.geometry}
          material={nodes.mesh_68.material}
          position={[-4, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_69.geometry}
          material={nodes.mesh_69.material}
          position={[-3, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_70.geometry}
          material={nodes.mesh_70.material}
          position={[-1, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_71.geometry}
          material={nodes.mesh_71.material}
          position={[0, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_72.geometry}
          material={nodes.mesh_72.material}
          position={[1, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_73.geometry}
          material={nodes.mesh_73.material}
          position={[3, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_74.geometry}
          material={nodes.mesh_74.material}
          position={[4, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_75.geometry}
          material={nodes.mesh_75.material}
          position={[5, -4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_76.geometry}
          material={nodes.mesh_76.material}
          position={[-3, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_77.geometry}
          material={nodes.mesh_77.material}
          position={[-1, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_78.geometry}
          material={nodes.mesh_78.material}
          position={[0, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_79.geometry}
          material={nodes.mesh_79.material}
          position={[1, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_80.geometry}
          material={nodes.mesh_80.material}
          position={[3, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_81.geometry}
          material={nodes.mesh_81.material}
          position={[2, -1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_82.geometry}
          material={nodes.mesh_82.material}
          position={[3, -1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_83.geometry}
          material={nodes.mesh_83.material}
          position={[1, -1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_84.geometry}
          material={nodes.mesh_84.material}
          position={[0, -1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_85.geometry}
          material={nodes.mesh_85.material}
          position={[-1, -1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_86.geometry}
          material={nodes.mesh_86.material}
          position={[-2, -1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_87.geometry}
          material={nodes.mesh_87.material}
          position={[-3, -1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_88.geometry}
          material={nodes.mesh_88.material}
          position={[-3, -2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_89.geometry}
          material={nodes.mesh_89.material}
          position={[-3, -3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_90.geometry}
          material={nodes.mesh_90.material}
          position={[-3, -4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_91.geometry}
          material={nodes.mesh_91.material}
          position={[-1, -2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_92.geometry}
          material={nodes.mesh_92.material}
          position={[-1, -3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_93.geometry}
          material={nodes.mesh_93.material}
          position={[-1, -4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_94.geometry}
          material={nodes.mesh_94.material}
          position={[0, -2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_95.geometry}
          material={nodes.mesh_95.material}
          position={[0, -3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_96.geometry}
          material={nodes.mesh_96.material}
          position={[0, -4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_97.geometry}
          material={nodes.mesh_97.material}
          position={[1, -2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_98.geometry}
          material={nodes.mesh_98.material}
          position={[-1, -5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_99.geometry}
          material={nodes.mesh_99.material}
          position={[-3, -5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_100.geometry}
          material={nodes.mesh_100.material}
          position={[0, -5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_101.geometry}
          material={nodes.mesh_101.material}
          position={[1, -3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_102.geometry}
          material={nodes.mesh_102.material}
          position={[1, -4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_103.geometry}
          material={nodes.mesh_103.material}
          position={[1, -5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_104.geometry}
          material={nodes.mesh_104.material}
          position={[3, -2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_105.geometry}
          material={nodes.mesh_105.material}
          position={[3, -3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_106.geometry}
          material={nodes.mesh_106.material}
          position={[3, -4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_107.geometry}
          material={nodes.mesh_107.material}
          position={[3, -5, -1]}
        />
      </group>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_108.geometry}
          material={nodes.mesh_108.material}
          position={[12, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_109.geometry}
          material={nodes.mesh_109.material}
          position={[13, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_110.geometry}
          material={nodes.mesh_110.material}
          position={[11, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_111.geometry}
          material={nodes.mesh_111.material}
          position={[12, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_112.geometry}
          material={nodes.mesh_112.material}
          position={[10, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_113.geometry}
          material={nodes.mesh_113.material}
          position={[11, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_114.geometry}
          material={nodes.mesh_114.material}
          position={[9, -1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_115.geometry}
          material={nodes.mesh_115.material}
          position={[10, -1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_116.geometry}
          material={nodes.mesh_116.material}
          position={[8, -2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_117.geometry}
          material={nodes.mesh_117.material}
          position={[9, -2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_118.geometry}
          material={nodes.mesh_118.material}
          position={[7, -3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_119.geometry}
          material={nodes.mesh_119.material}
          position={[8, -3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_120.geometry}
          material={nodes.mesh_120.material}
          position={[6, -4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_121.geometry}
          material={nodes.mesh_121.material}
          position={[7, -4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_122.geometry}
          material={nodes.mesh_122.material}
          position={[6, -5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_123.geometry}
          material={nodes.mesh_123.material}
          position={[5, -6, 1]}
        />
      </group>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_124.geometry}
          material={nodes.mesh_124.material}
          position={[-5, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_125.geometry}
          material={nodes.mesh_125.material}
          position={[-4, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_126.geometry}
          material={nodes.mesh_126.material}
          position={[4, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_127.geometry}
          material={nodes.mesh_127.material}
          position={[5, -5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_128.geometry}
          material={nodes.mesh_128.material}
          position={[-3, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_129.geometry}
          material={nodes.mesh_129.material}
          position={[-2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_130.geometry}
          material={nodes.mesh_130.material}
          position={[-1, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_131.geometry}
          material={nodes.mesh_131.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_132.geometry}
          material={nodes.mesh_132.material}
          position={[1, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_133.geometry}
          material={nodes.mesh_133.material}
          position={[2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_134.geometry}
          material={nodes.mesh_134.material}
          position={[3, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_135.geometry}
          material={nodes.mesh_135.material}
          position={[4, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_136.geometry}
          material={nodes.mesh_136.material}
          position={[-4, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_137.geometry}
          material={nodes.mesh_137.material}
          position={[-3, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_138.geometry}
          material={nodes.mesh_138.material}
          position={[-2, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_139.geometry}
          material={nodes.mesh_139.material}
          position={[-1, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_140.geometry}
          material={nodes.mesh_140.material}
          position={[0, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_141.geometry}
          material={nodes.mesh_141.material}
          position={[1, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_142.geometry}
          material={nodes.mesh_142.material}
          position={[2, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_143.geometry}
          material={nodes.mesh_143.material}
          position={[3, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_144.geometry}
          material={nodes.mesh_144.material}
          position={[4, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_145.geometry}
          material={nodes.mesh_145.material}
          position={[5, 1, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_146.geometry}
          material={nodes.mesh_146.material}
          position={[-4, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_147.geometry}
          material={nodes.mesh_147.material}
          position={[-3, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_148.geometry}
          material={nodes.mesh_148.material}
          position={[-2, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_149.geometry}
          material={nodes.mesh_149.material}
          position={[-1, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_150.geometry}
          material={nodes.mesh_150.material}
          position={[0, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_151.geometry}
          material={nodes.mesh_151.material}
          position={[1, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_152.geometry}
          material={nodes.mesh_152.material}
          position={[2, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_153.geometry}
          material={nodes.mesh_153.material}
          position={[3, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_154.geometry}
          material={nodes.mesh_154.material}
          position={[4, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_155.geometry}
          material={nodes.mesh_155.material}
          position={[5, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_156.geometry}
          material={nodes.mesh_156.material}
          position={[-4, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_157.geometry}
          material={nodes.mesh_157.material}
          position={[-3, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_158.geometry}
          material={nodes.mesh_158.material}
          position={[-2, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_159.geometry}
          material={nodes.mesh_159.material}
          position={[-1, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_160.geometry}
          material={nodes.mesh_160.material}
          position={[0, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_161.geometry}
          material={nodes.mesh_161.material}
          position={[1, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_162.geometry}
          material={nodes.mesh_162.material}
          position={[2, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_163.geometry}
          material={nodes.mesh_163.material}
          position={[3, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_164.geometry}
          material={nodes.mesh_164.material}
          position={[4, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_165.geometry}
          material={nodes.mesh_165.material}
          position={[5, 3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_166.geometry}
          material={nodes.mesh_166.material}
          position={[-4, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_167.geometry}
          material={nodes.mesh_167.material}
          position={[-3, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_168.geometry}
          material={nodes.mesh_168.material}
          position={[-2, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_169.geometry}
          material={nodes.mesh_169.material}
          position={[-1, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_170.geometry}
          material={nodes.mesh_170.material}
          position={[0, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_171.geometry}
          material={nodes.mesh_171.material}
          position={[1, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_172.geometry}
          material={nodes.mesh_172.material}
          position={[2, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_173.geometry}
          material={nodes.mesh_173.material}
          position={[3, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_174.geometry}
          material={nodes.mesh_174.material}
          position={[4, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_175.geometry}
          material={nodes.mesh_175.material}
          position={[5, 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_176.geometry}
          material={nodes.mesh_176.material}
          position={[-4, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_177.geometry}
          material={nodes.mesh_177.material}
          position={[-3, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_178.geometry}
          material={nodes.mesh_178.material}
          position={[-2, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_179.geometry}
          material={nodes.mesh_179.material}
          position={[-1, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_180.geometry}
          material={nodes.mesh_180.material}
          position={[0, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_181.geometry}
          material={nodes.mesh_181.material}
          position={[1, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_182.geometry}
          material={nodes.mesh_182.material}
          position={[2, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_183.geometry}
          material={nodes.mesh_183.material}
          position={[3, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_184.geometry}
          material={nodes.mesh_184.material}
          position={[4, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_185.geometry}
          material={nodes.mesh_185.material}
          position={[5, 5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_186.geometry}
          material={nodes.mesh_186.material}
          position={[-3, 6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_187.geometry}
          material={nodes.mesh_187.material}
          position={[-2, 6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_188.geometry}
          material={nodes.mesh_188.material}
          position={[-1, 6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_189.geometry}
          material={nodes.mesh_189.material}
          position={[0, 6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_190.geometry}
          material={nodes.mesh_190.material}
          position={[1, 6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_191.geometry}
          material={nodes.mesh_191.material}
          position={[2, 6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_192.geometry}
          material={nodes.mesh_192.material}
          position={[3, 6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_193.geometry}
          material={nodes.mesh_193.material}
          position={[4, 6, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_194.geometry}
          material={nodes.mesh_194.material}
          position={[-3, 0, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_195.geometry}
          material={nodes.mesh_195.material}
          position={[-2, 0, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_196.geometry}
          material={nodes.mesh_196.material}
          position={[-1, 0, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_197.geometry}
          material={nodes.mesh_197.material}
          position={[0, 0, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_198.geometry}
          material={nodes.mesh_198.material}
          position={[1, 0, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_199.geometry}
          material={nodes.mesh_199.material}
          position={[2, 0, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_200.geometry}
          material={nodes.mesh_200.material}
          position={[3, 0, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_201.geometry}
          material={nodes.mesh_201.material}
          position={[4, 0, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_202.geometry}
          material={nodes.mesh_202.material}
          position={[-4, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_203.geometry}
          material={nodes.mesh_203.material}
          position={[-3, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_204.geometry}
          material={nodes.mesh_204.material}
          position={[-2, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_205.geometry}
          material={nodes.mesh_205.material}
          position={[-1, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_206.geometry}
          material={nodes.mesh_206.material}
          position={[0, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_207.geometry}
          material={nodes.mesh_207.material}
          position={[1, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_208.geometry}
          material={nodes.mesh_208.material}
          position={[2, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_209.geometry}
          material={nodes.mesh_209.material}
          position={[3, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_210.geometry}
          material={nodes.mesh_210.material}
          position={[4, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_211.geometry}
          material={nodes.mesh_211.material}
          position={[5, 1, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_212.geometry}
          material={nodes.mesh_212.material}
          position={[-4, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_213.geometry}
          material={nodes.mesh_213.material}
          position={[-3, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_214.geometry}
          material={nodes.mesh_214.material}
          position={[-2, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_215.geometry}
          material={nodes.mesh_215.material}
          position={[-1, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_216.geometry}
          material={nodes.mesh_216.material}
          position={[0, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_217.geometry}
          material={nodes.mesh_217.material}
          position={[1, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_218.geometry}
          material={nodes.mesh_218.material}
          position={[2, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_219.geometry}
          material={nodes.mesh_219.material}
          position={[3, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_220.geometry}
          material={nodes.mesh_220.material}
          position={[4, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_221.geometry}
          material={nodes.mesh_221.material}
          position={[5, 2, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_222.geometry}
          material={nodes.mesh_222.material}
          position={[-4, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_223.geometry}
          material={nodes.mesh_223.material}
          position={[-3, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_224.geometry}
          material={nodes.mesh_224.material}
          position={[-2, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_225.geometry}
          material={nodes.mesh_225.material}
          position={[-1, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_226.geometry}
          material={nodes.mesh_226.material}
          position={[0, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_227.geometry}
          material={nodes.mesh_227.material}
          position={[1, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_228.geometry}
          material={nodes.mesh_228.material}
          position={[2, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_229.geometry}
          material={nodes.mesh_229.material}
          position={[3, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_230.geometry}
          material={nodes.mesh_230.material}
          position={[4, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_231.geometry}
          material={nodes.mesh_231.material}
          position={[5, 3, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_232.geometry}
          material={nodes.mesh_232.material}
          position={[-4, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_233.geometry}
          material={nodes.mesh_233.material}
          position={[-3, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_234.geometry}
          material={nodes.mesh_234.material}
          position={[-2, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_235.geometry}
          material={nodes.mesh_235.material}
          position={[-1, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_236.geometry}
          material={nodes.mesh_236.material}
          position={[0, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_237.geometry}
          material={nodes.mesh_237.material}
          position={[1, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_238.geometry}
          material={nodes.mesh_238.material}
          position={[2, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_239.geometry}
          material={nodes.mesh_239.material}
          position={[3, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_240.geometry}
          material={nodes.mesh_240.material}
          position={[4, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_241.geometry}
          material={nodes.mesh_241.material}
          position={[5, 4, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_242.geometry}
          material={nodes.mesh_242.material}
          position={[-4, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_243.geometry}
          material={nodes.mesh_243.material}
          position={[-3, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_244.geometry}
          material={nodes.mesh_244.material}
          position={[-2, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_245.geometry}
          material={nodes.mesh_245.material}
          position={[-1, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_246.geometry}
          material={nodes.mesh_246.material}
          position={[0, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_247.geometry}
          material={nodes.mesh_247.material}
          position={[1, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_248.geometry}
          material={nodes.mesh_248.material}
          position={[2, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_249.geometry}
          material={nodes.mesh_249.material}
          position={[3, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_250.geometry}
          material={nodes.mesh_250.material}
          position={[4, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_251.geometry}
          material={nodes.mesh_251.material}
          position={[5, 5, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_252.geometry}
          material={nodes.mesh_252.material}
          position={[-3, 6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_253.geometry}
          material={nodes.mesh_253.material}
          position={[-2, 6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_254.geometry}
          material={nodes.mesh_254.material}
          position={[-1, 6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_255.geometry}
          material={nodes.mesh_255.material}
          position={[0, 6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_256.geometry}
          material={nodes.mesh_256.material}
          position={[1, 6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_257.geometry}
          material={nodes.mesh_257.material}
          position={[2, 6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_258.geometry}
          material={nodes.mesh_258.material}
          position={[3, 6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_259.geometry}
          material={nodes.mesh_259.material}
          position={[4, 6, -1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_260.geometry}
          material={nodes.mesh_260.material}
          position={[-3, 0, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_261.geometry}
          material={nodes.mesh_261.material}
          position={[-2, 0, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_262.geometry}
          material={nodes.mesh_262.material}
          position={[-1, 0, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_263.geometry}
          material={nodes.mesh_263.material}
          position={[0, 0, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_264.geometry}
          material={nodes.mesh_264.material}
          position={[1, 0, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_265.geometry}
          material={nodes.mesh_265.material}
          position={[2, 0, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_266.geometry}
          material={nodes.mesh_266.material}
          position={[3, 0, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_267.geometry}
          material={nodes.mesh_267.material}
          position={[-4, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_268.geometry}
          material={nodes.mesh_268.material}
          position={[-3, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_269.geometry}
          material={nodes.mesh_269.material}
          position={[-2, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_270.geometry}
          material={nodes.mesh_270.material}
          position={[-1, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_271.geometry}
          material={nodes.mesh_271.material}
          position={[0, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_272.geometry}
          material={nodes.mesh_272.material}
          position={[1, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_273.geometry}
          material={nodes.mesh_273.material}
          position={[2, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_274.geometry}
          material={nodes.mesh_274.material}
          position={[3, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_275.geometry}
          material={nodes.mesh_275.material}
          position={[4, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_276.geometry}
          material={nodes.mesh_276.material}
          position={[5, 1, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_277.geometry}
          material={nodes.mesh_277.material}
          position={[-4, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_278.geometry}
          material={nodes.mesh_278.material}
          position={[-3, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_279.geometry}
          material={nodes.mesh_279.material}
          position={[-2, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_280.geometry}
          material={nodes.mesh_280.material}
          position={[-1, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_281.geometry}
          material={nodes.mesh_281.material}
          position={[0, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_282.geometry}
          material={nodes.mesh_282.material}
          position={[1, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_283.geometry}
          material={nodes.mesh_283.material}
          position={[2, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_284.geometry}
          material={nodes.mesh_284.material}
          position={[3, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_285.geometry}
          material={nodes.mesh_285.material}
          position={[4, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_286.geometry}
          material={nodes.mesh_286.material}
          position={[5, 2, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_287.geometry}
          material={nodes.mesh_287.material}
          position={[-4, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_288.geometry}
          material={nodes.mesh_288.material}
          position={[-3, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_289.geometry}
          material={nodes.mesh_289.material}
          position={[-2, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_290.geometry}
          material={nodes.mesh_290.material}
          position={[-1, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_291.geometry}
          material={nodes.mesh_291.material}
          position={[0, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_292.geometry}
          material={nodes.mesh_292.material}
          position={[1, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_293.geometry}
          material={nodes.mesh_293.material}
          position={[2, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_294.geometry}
          material={nodes.mesh_294.material}
          position={[3, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_295.geometry}
          material={nodes.mesh_295.material}
          position={[4, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_296.geometry}
          material={nodes.mesh_296.material}
          position={[5, 3, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_297.geometry}
          material={nodes.mesh_297.material}
          position={[-4, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_298.geometry}
          material={nodes.mesh_298.material}
          position={[-3, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_299.geometry}
          material={nodes.mesh_299.material}
          position={[-2, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_300.geometry}
          material={nodes.mesh_300.material}
          position={[-1, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_301.geometry}
          material={nodes.mesh_301.material}
          position={[0, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_302.geometry}
          material={nodes.mesh_302.material}
          position={[1, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_303.geometry}
          material={nodes.mesh_303.material}
          position={[2, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_304.geometry}
          material={nodes.mesh_304.material}
          position={[3, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_305.geometry}
          material={nodes.mesh_305.material}
          position={[4, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_306.geometry}
          material={nodes.mesh_306.material}
          position={[5, 4, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_307.geometry}
          material={nodes.mesh_307.material}
          position={[-3, 5, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_308.geometry}
          material={nodes.mesh_308.material}
          position={[-2, 5, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_309.geometry}
          material={nodes.mesh_309.material}
          position={[-1, 5, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_310.geometry}
          material={nodes.mesh_310.material}
          position={[0, 5, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_311.geometry}
          material={nodes.mesh_311.material}
          position={[1, 5, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_312.geometry}
          material={nodes.mesh_312.material}
          position={[2, 5, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_313.geometry}
          material={nodes.mesh_313.material}
          position={[3, 5, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_314.geometry}
          material={nodes.mesh_314.material}
          position={[4, 5, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_315.geometry}
          material={nodes.mesh_315.material}
          position={[-3, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_316.geometry}
          material={nodes.mesh_316.material}
          position={[-2, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_317.geometry}
          material={nodes.mesh_317.material}
          position={[-1, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_318.geometry}
          material={nodes.mesh_318.material}
          position={[0, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_319.geometry}
          material={nodes.mesh_319.material}
          position={[1, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_320.geometry}
          material={nodes.mesh_320.material}
          position={[2, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_321.geometry}
          material={nodes.mesh_321.material}
          position={[3, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_322.geometry}
          material={nodes.mesh_322.material}
          position={[4, 0, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_323.geometry}
          material={nodes.mesh_323.material}
          position={[-4, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_324.geometry}
          material={nodes.mesh_324.material}
          position={[-3, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_325.geometry}
          material={nodes.mesh_325.material}
          position={[-2, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_326.geometry}
          material={nodes.mesh_326.material}
          position={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_327.geometry}
          material={nodes.mesh_327.material}
          position={[0, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_328.geometry}
          material={nodes.mesh_328.material}
          position={[1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_329.geometry}
          material={nodes.mesh_329.material}
          position={[2, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_330.geometry}
          material={nodes.mesh_330.material}
          position={[3, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_331.geometry}
          material={nodes.mesh_331.material}
          position={[4, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_332.geometry}
          material={nodes.mesh_332.material}
          position={[5, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_333.geometry}
          material={nodes.mesh_333.material}
          position={[-4, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_334.geometry}
          material={nodes.mesh_334.material}
          position={[-3, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_335.geometry}
          material={nodes.mesh_335.material}
          position={[-2, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_336.geometry}
          material={nodes.mesh_336.material}
          position={[-1, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_337.geometry}
          material={nodes.mesh_337.material}
          position={[0, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_338.geometry}
          material={nodes.mesh_338.material}
          position={[1, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_339.geometry}
          material={nodes.mesh_339.material}
          position={[2, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_340.geometry}
          material={nodes.mesh_340.material}
          position={[3, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_341.geometry}
          material={nodes.mesh_341.material}
          position={[4, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_342.geometry}
          material={nodes.mesh_342.material}
          position={[5, 2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_343.geometry}
          material={nodes.mesh_343.material}
          position={[-4, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_344.geometry}
          material={nodes.mesh_344.material}
          position={[-3, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_345.geometry}
          material={nodes.mesh_345.material}
          position={[-2, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_346.geometry}
          material={nodes.mesh_346.material}
          position={[-1, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_347.geometry}
          material={nodes.mesh_347.material}
          position={[0, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_348.geometry}
          material={nodes.mesh_348.material}
          position={[1, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_349.geometry}
          material={nodes.mesh_349.material}
          position={[2, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_350.geometry}
          material={nodes.mesh_350.material}
          position={[3, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_351.geometry}
          material={nodes.mesh_351.material}
          position={[4, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_352.geometry}
          material={nodes.mesh_352.material}
          position={[5, 3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_353.geometry}
          material={nodes.mesh_353.material}
          position={[-4, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_354.geometry}
          material={nodes.mesh_354.material}
          position={[-3, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_355.geometry}
          material={nodes.mesh_355.material}
          position={[-2, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_356.geometry}
          material={nodes.mesh_356.material}
          position={[-1, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_357.geometry}
          material={nodes.mesh_357.material}
          position={[0, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_358.geometry}
          material={nodes.mesh_358.material}
          position={[1, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_359.geometry}
          material={nodes.mesh_359.material}
          position={[2, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_360.geometry}
          material={nodes.mesh_360.material}
          position={[3, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_361.geometry}
          material={nodes.mesh_361.material}
          position={[4, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_362.geometry}
          material={nodes.mesh_362.material}
          position={[5, 4, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_363.geometry}
          material={nodes.mesh_363.material}
          position={[-4, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_364.geometry}
          material={nodes.mesh_364.material}
          position={[-3, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_365.geometry}
          material={nodes.mesh_365.material}
          position={[-2, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_366.geometry}
          material={nodes.mesh_366.material}
          position={[-1, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_367.geometry}
          material={nodes.mesh_367.material}
          position={[0, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_368.geometry}
          material={nodes.mesh_368.material}
          position={[1, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_369.geometry}
          material={nodes.mesh_369.material}
          position={[2, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_370.geometry}
          material={nodes.mesh_370.material}
          position={[3, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_371.geometry}
          material={nodes.mesh_371.material}
          position={[4, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_372.geometry}
          material={nodes.mesh_372.material}
          position={[5, 5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_373.geometry}
          material={nodes.mesh_373.material}
          position={[-3, 6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_374.geometry}
          material={nodes.mesh_374.material}
          position={[-2, 6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_375.geometry}
          material={nodes.mesh_375.material}
          position={[-1, 6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_376.geometry}
          material={nodes.mesh_376.material}
          position={[0, 6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_377.geometry}
          material={nodes.mesh_377.material}
          position={[1, 6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_378.geometry}
          material={nodes.mesh_378.material}
          position={[2, 6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_379.geometry}
          material={nodes.mesh_379.material}
          position={[3, 6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_380.geometry}
          material={nodes.mesh_380.material}
          position={[4, 6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_381.geometry}
          material={nodes.mesh_381.material}
          position={[-5, 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_382.geometry}
          material={nodes.mesh_382.material}
          position={[-5, 3, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/70703.glb')
