/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Hall(props) {
  const { nodes, materials } = useGLTF("/hall-transformed.glb");

  materials.VenatorV3_SmallDoor_WallLight.emissiveIntensity = 3;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.012}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1448.93, -5.342, -159.366]} scale={6.463}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.WallPanel21_VenatorV3_WallPanels_0001.geometry}
              material={materials.VenatorV3_WallPanels}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.WallPanel21_VenatorV3_WallPanels_0001_1.geometry}
              material={materials.VenatorV3_LargeDoor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.WallPanel21_VenatorV3_WallPanels_0001_2.geometry}
              material={materials.Venator_Floor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.WallPanel21_VenatorV3_WallPanels_0001_3.geometry}
              material={materials.VenatorV3_SmallDoor_WallLight}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/hall-transformed.glb");
