/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Probe(props) {
  const { nodes, materials } = useGLTF("/probe-transformed.glb");
  materials.light.emissiveIntensity = 20;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.423, 0.036, -0.084]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["cam_low_Material_#26_0_1"].geometry}
          material={materials.Material_26}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["cam_low_Material_#26_0_2"].geometry}
          material={materials.light}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["ball_low_Material_#26_0"].geometry}
        material={materials.Material_26}
        position={[-0.423, 0.036, -0.084]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["d_low_Material_#26_0"].geometry}
        material={materials.Material_26}
        position={[-0.423, 0.036, -0.084]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["inner_low_Material_#26_0"].geometry}
        material={materials.Material_26}
        position={[-0.211, -0.033, 7.813]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Object018_Material_#26_0"].geometry}
        material={materials.light}
        position={[-0.423, 0.036, -0.084]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["shell_low_Material_#26_0"].geometry}
        position={[-0.423, 0.036, -0.084]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <meshPhysicalMaterial
          color="grey"
          roughness={0.2}
          metalness={0.9}
          emissive="white"
          emissiveIntensity={0.2}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/probe-transformed.glb");
